### ISSUE TITLE
No output while using "--verbose" parameter

### ISSUE THREAD

**Issue by mdziczkowski** [lfreist/hwinfo#108]
## System info:

- **OS**: Debian (codename: bookworm)
- **hwinfo version**: 21.82-1
- **Install method**: Debian repository

## Issue description

- **Used command**:

`hwinfo --all --map --verbose --log filename.txt`

### Expected result

Verbose hardware informations

### Current result

No output.

Note: When used `hwinfo` without parameters, I recieved a sumarized output

**Comment by lfreist** [comment]
Hi, you may were looking for this repository: https://github.com/openSUSE/hwinfo

**Comment by mdziczkowski** [comment]
> Hi, you may were looking for this repository: https://github.com/openSUSE/hwinfo

I was searching for one with is maintained by Debian because thru it's reposirory it was installed

**Comment by lfreist** [comment]
https://salsa.debian.org/debian/hwinfo
