### ISSUE TITLE
arm linux __get_cpuid_count function undefine

### ISSUE THREAD

**Issue by xinsuinizhuan** [lfreist/hwinfo#19]
__get_cpuid_count(func_id, sub_func_id, &regs[0], &regs[1], &regs[2], &regs[3]);
__get_cpuid_count function undefine

jetson arm unbuntu linux

**Comment by lfreist** [comment]
ARM does not support the cpuid instructions (x86 specific).

However, I have just looked into the code and fixed an import. Can you try if it is working now? Thank you!

**Comment by xinsuinizhuan** [comment]
it do not work

**Comment by lfreist** [comment]
I assume the error occurs in `cpuid.h`. This file is only used if the compiler recognizes your machine as x86. In your case, the file should not be included.

Could you please check what macro makes `HWINFO_X86` defined in the following file/line: https://github.com/lfreist/hwinfo/blob/main/include/hwinfo/platform.h#L19

Sadly, I do not have an ARM machine to check it out myself...

**Comment by xinsuinizhuan** [comment]
how about arm linux，now?

**Comment by lfreist** [comment]
Hi, Could you please provide more information about the issue?
Hardware, Compiler, ...

**Comment by facug91** [comment]
With this recently accepted PR #28, and this new PR #29 I just did, I've been able to compile and run `Example` in a Jetson Xavier.

**Comment by facug91** [comment]
The problem was that Jetsons have Ubuntu 18.04, which has GCC 8.4 by default, which doesn't support C++20, and even with C++17, you need to link to "stdc++fs" to use `std::filesystem`.

**Comment by lfreist** [comment]
Thank you Facundo!

PR #29 is merged!

**Comment by facug91** [comment]
Just to fix the wrong comment I made, Ubuntu 18.04 comes with gcc 7 installed by default, which doesn't even have C++17 support. In Jetsons you can install gcc 8, which allows you to use CUDA 10.2, and compile with C++17.
