### ISSUE TITLE
All main board methods return <unknown> on Windows

### ISSUE THREAD

**Issue by dmitr-fedorov** [lfreist/hwinfo#36]
The README says that almost all the MainBoard methods are implemented, but they return < unknown > for me.
Can it be the problem on my end or the methods are really not implemented properly?

**Comment by lfreist** [comment]
Hi!

The methods are implemented and work on my test systems.

May I ask, what windows version and compiler you used?

**Comment by dmitr-fedorov** [comment]
I use Windows 10 and MSVC 14.3 compiler.

**Comment by lfreist** [comment]
I am currently on Holliday. I'll check this next week! There might got a bug into this in one of the last commits...
