### ISSUE TITLE
#include <optional> cpu.h:7:20: fatal error: optional: No such file or directory

### ISSUE THREAD

**Issue by double2li** [lfreist/hwinfo#43]
in arm64 debian9 , gcc 6.3.0，compile error
#include <optional> cpu.h:7:20: fatal error: optional: No such file or directory

**Comment by lfreist** [comment]
Hi!

Thank you for your report. 'std::optional' is a c++17 feature. However, afaik gcc v.6.3 does not support it yet.

I am currently working on moving the library back to C++11 and didn't notice the problem of using optional yet. I will provide a fix in the next days.

Until then, it might be that using '#include <experimental/optional>' works with gcc v.6.3, but I am not sure about it...

**Comment by lfreist** [comment]
I have just realised that the use of `std::optional` already was removed but the include statement was not. I removed it and it should work by now.
