### ISSUE TITLE
Why OS Architecture not the same on my windows system info?

### ISSUE THREAD

**Issue by fiantyogalihp** [lfreist/hwinfo#46]
My code:
`hwinfo::OS os;
std::cout << "----------------------------------- OS ------------------------------------" << std::endl;

std::cout << std::left << std::setw(20) << "Operating System:";

std::cout << os.fullName() << std::endl;

std::cout << std::left << std::setw(20) << "short name:";

std::cout << os.name() << std::endl;

std::cout << std::left << std::setw(20) << "version:";

std::cout << os.version() << std::endl;

std::cout << std::left << std::setw(20) << "kernel:";

std::cout << os.kernel() << std::endl;

std::cout << std::left << std::setw(20) << "architecture:";

std::cout << (os.is32bit() ? "32 bit" : "64 bit") << std::endl;

std::cout << std::left << std::setw(20) << "endianess:";

std::cout << (os.isLittleEndian() ? "little endian" : "big endian") << std::endl;`

My code result
![image](https://github.com/lfreist/hwinfo/assets/88466328/92413849-b801-455b-911a-1fdf536d01be)

My windows System Information:
![Screenshot 2023-07-07 113123](https://github.com/lfreist/hwinfo/assets/88466328/a61b84a6-013a-43ca-989f-ccdad64d39bb)

**Comment by lfreist** [comment]
Hi, Thank you for the report.

This bug is new to me and I could not reproduce it on my Windows machine. However, I have tried to harden the code responsible for the bit-architecture report  in this [commit](https://github.com/lfreist/hwinfo/commit/aab7bd288666e68c81f42b65b9e9cbd545d817c4). Could you please check, if it is working now?

**Comment by fiantyogalihp** [comment]
Thanks very much, now it's working at all 👍 

My code is same to your [example.cpp](https://github.com/lfreist/hwinfo/blob/main/examples/example.cpp), and my result code:
![Screenshot 2023-07-07 201656](https://github.com/lfreist/hwinfo/assets/88466328/fb531cc5-1284-4304-9dd9-503c3db5f5fb)


---
Oh ya... you got typo in your [example.cpp](https://github.com/lfreist/hwinfo/blob/main/examples/example.cpp) on line **[103](https://github.com/lfreist/hwinfo/blob/aab7bd288666e68c81f42b65b9e9cbd545d817c4/examples/example.cpp#L103)** at Main Board serial number :)

**Comment by lfreist** [comment]
Thanks for sharing your result and happy that I could fix the bug.

You might want to contribute your implementations of kernel and version to this library since they are empty for windows at the moment.
