### ISSUE TITLE
Msys2/MinGW build doesn't work on Windows

### ISSUE THREAD

**Issue by lcjuanpa** [lfreist/hwinfo#48]
Hello @lfreist

I have built successfully hwinfo on Windows 10 using [Msys2](https://www.msys2.org/) using next commands:

> git clone https://github.com/lfreist/hwinfo
> cd hwinfo
> mkdir build
> cd build
> cmake **-G "MinGW Makefiles"** -DCMAKE_BUILD_TYPE=Release ..
> make

However running Example.exe no hardware info is displayed. See next picture:
![hwinfoOutput](https://github.com/lfreist/hwinfo/assets/30904688/39407432-140f-4f27-8ed9-f12d2df3bbbe)
I saw there is a version for Visual Studio however I am working with open source tools. 
Can you help me to fix this issue?
Is it possible to use hwinfo with Msys2 environment?

**Comment by lfreist** [comment]
Hi!

HWinfo uses WMI classes for querying hardware information on windows. As far as I know, this is not supported with Msys2...
