### ISSUE TITLE
Make OpenCL an optional dependency

### ISSUE THREAD

**Issue by diiigle** [lfreist/hwinfo#54]
Is there any way to make OpenCL (quite a heavy chunk to the otherwise small and lightweight library) _fully_ optional?
I see you have a CMake option to not use it, however git submodules still downloads the whole subtree, even if one doesn't want it.

https://cmake.org/cmake/help/latest/module/FetchContent.html comes to mind.

**Comment by lfreist** [comment]
Hi, valid point! I'll check the options and will change how OpenCL is added.

**Comment by barracuda156** [comment]
Yes, please. At the moment it does not work correctly at all:
```
CMake Error at external/miss-opencl/CMakeLists.txt:22 (add_subdirectory):
  The source directory

    /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_hwinfo/hwinfo/work/hwinfo-a1ae945ab784780af5fc166150a6f6612d41e7bf/external/miss-opencl/external/OpenCL

  does not contain a CMakeLists.txt file.


-- Configuring incomplete, errors occurred!
```

**Comment by lfreist** [comment]
You need to run `git update --init --recursive` first. However, building on Mac has some issues atm since I do not have access to a Mac...

**Comment by lfreist** [comment]
Yes, OpenCL kind of is an overkill, but for now, I found no other way to retrieve GPU Memory information...

**Comment by F35H** [comment]
I would suggest removing GPU information from the library entirely. If people need information about the GPU, getting it from Vulkan, DirectX, OpenGL, or OpenCL is already really well documented. Those standards [and similar] are really the only places people would need it anyhow. 

I'm not trying to be rude, but there really is zero reason to include it. For people who are already using one of these frameworks, adding OpenCL on top of it is unacceptable in most cases especially considering OpenCL is on its way out the door to be replaced with other alternative frameworks.

**Comment by lfreist** [comment]
Thank you for your thoughts. I think, that modularity would indeed increase the library's usability.

I'll take this task as soon as possible. Coworkers and ideas are welcome!

**Comment by lfreist** [comment]
Continued in #94
