### ISSUE TITLE
RAM on Windows only returns the information for 1 DIMM

### ISSUE THREAD

**Issue by ruifig** [lfreist/hwinfo#64]
I have 2 DIMMs, and it seems hwinfo only reports half the RAM (1 DIMM).

I can see that in windows/ram.cpp, we are not iterating through the WMI results.  We are only grabbing the first one.

**Comment by ruifig** [comment]
Seems like this is happening on Linux too.
Testing with WSL (Windows Subsystem for Linux), and it's reporting half of what it should.

**Comment by lfreist** [comment]
Hi,
Thank you for the report! You are absolutely correct. Will fix it in the next days and update this issue as soon as the fix is published.

**Comment by lfreist** [comment]
Hi @ruifig ,
I have fixed the issue for windows: c30c30eee66b2487f9ca51d5da53d64fa2c3790d
