### ISSUE TITLE
Mingw64 a build problem

### ISSUE THREAD

**Issue by zzopuh** [lfreist/hwinfo#89]
Hello,
I am trying to build HWinfo with gcc13.2.0 Mingw64 win10 x86 platform.
And I have got the linker issue:
**[build] [100%] Linking CXX executable HWExample.exe
[build] C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../../lib/libHWinfo.a(wmi_wrapper.cpp.obj):wmi_wrapper.cp:(.text+0xc8): undefined reference to `_com_util::ConvertStringToBSTR(char const*)'**

Is it possible to build HWinfo windows version and access WMI without visual studio and its libraries?

**Comment by lfreist** [comment]
HWinfo is quite dependant on the windows API for hardware information on windows. Thus, the only supported compiler for HWinfo on windows is MSVC
