### ISSUE TITLE
Make HWinfo modular

### ISSUE THREAD

**Issue by lfreist** [lfreist/hwinfo#94]
I would suggest removing GPU information from the library entirely. If people need information about the GPU, getting it from Vulkan, DirectX, OpenGL, or OpenCL is already really well documented. Those standards [and similar] are really the only places people would need it anyhow. 

I would suggest removing GPU information from the library entirely. If people need information about the GPU, getting it from Vulkan, DirectX, OpenGL, or OpenCL is already really well documented. Those standards [and similar] are really the only places people would need it anyhow. 

I'm not trying to be rude, but there really is zero reason to include it. For people who are already using one of these frameworks, adding OpenCL on top of it is unacceptable in most cases especially considering OpenCL is on its way out the door to be replaced with other alternative frameworks.

Edit: Had a quick think. It'd probably be better to make the entire library modular. You already have the library well divided as appropriate, making it modular seems like a very safe next step. In other words, I mean making the motherboard, battery, CPU, etc. dependent on user choice. 

_original post by @F35H in https://github.com/lfreist/hwinfo/issues/54#issuecomment-2212381153_

**Comment by aminya** [comment]
There are still benefits to providing this information. That's the point of giving a cross-platform way to know the hardware information. However, we can guard these features using compile flags.

**Comment by lfreist** [comment]
Yes, the plan is to continue supporting GPU using OpenCL (and maybe also other backends...) but provide the information of the hardware components in modules (as CMake targets hwinfo_[gpu|cpu|ram|disk|mainboard|...])
